# spring.datasource.url=jdbc:mysql://localhost:3306/todos_db
# spring.datasource.username=root
# spring.datasource.password=aaaaaaaa
# spring.datasource.url=jdbc:mysql://u9xu7qf3ozwvnrup:wuzJh5ubPR53RwzmzG2z@bfvsw7hgaoyhngma4jlj-mysql.services.clever-cloud.com:3306/bfvsw7hgaoyhngma4jlj
# spring.datasource.username=u9xu7qf3ozwvnrup
# spring.datasource.password=wuzJh5ubPR53RwzmzG2z
spring.datasource.url=jdbc:mysql://sandboxdb.c1ycgwocye37.ap-southeast-2.rds.amazonaws.com:3306/Todos
spring.datasource.username=admin
spring.datasource.password=password
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# debug: true
# MYSQL_ADDON_HOST=bfvsw7hgaoyhngma4jlj-mysql.services.clever-cloud.com
# MYSQL_ADDON_DB=bfvsw7hgaoyhngma4jlj
# MYSQL_ADDON_USER=u9xu7qf3ozwvnrup
# MYSQL_ADDON_PORT=3306
# MYSQL_ADDON_PASSWORD=wuzJh5ubPR53RwzmzG2z
# MYSQL_ADDON_URI=mysql://u9xu7qf3ozwvnrup:wuzJh5ubPR53RwzmzG2z@bfvsw7hgaoyhngma4jlj-mysql.services.clever-cloud.com:3306/bfvsw7hgaoyhngma4jlj